### ISSUE TITLE
Handling text wrapping in Two.Text

### ISSUE THREAD

**Issue by joex92** [jonobr1/two.js#687]
Hi,
I'm showing text on a SVG canvas, everything is fine, the only issue I'm having is when the text showing is too long.
How do I handle that? I tried with a `.wrap` class, but that doesn't work:
```js
tText.className = '.wrap';
```
```css
.wrap {
  overflow-wrap: break-word; 
	width: 100vw;
	height: 100vh;
}
```
how can I wrap text?

it looks like this:
![image](https://user-images.githubusercontent.com/645579/215152844-a25ec8f5-1c49-4a81-9a91-ac530d402393.png)
(just using example texts)
